# Generated by Django 5.1.6 on 2025-03-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='法人名')),
                ('representative_name', models.CharField(max_length=255, verbose_name='代表者名')),
                ('company_number', models.CharField(max_length=255, unique=True, verbose_name='法人番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=255, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
